server:
  port: 8001
spring:
  application:
    name: snowflake-plus-sample
snowflake:
  plus:
    #local: 本地配置模式，zookeeper: 注册中心模式，ip: IP地址模式
    work-type: zookeeper
    #应用注册名
    name: snowflake-plus-sample
    #应用注册端口
    listen-port: 8001
    #zookeeper地址
    address: localhost:2181
    #ID生成的初始时间
    start-time: 1564617600000
    #workerId的bit位数
    worker-id-bits: 8
    #sequence的bit位数
    sequence-bits: 12
