server:
  port: 8001
spring:
  application:
    name: snowflake-plus-sample
snowflake:
  plus:
    #the supported types are local(local config file mode), zookeeper and ip.
    work-type: zookeeper
    #initial start time, default: 2019-08-01 00:00:00 (UTC)
    start-time: 1564617600000
    #the number of bit for worker id, default: 8bit
    worker-id-bits: 8
    #the number of bit for sequence, default: 12bit
    sequence-bits: 12
    #the application's registered name
    name: snowflake-plus-sample
    #the application's registered port
    listen-port: 8001
    #the zookeeper address
    address: localhost:2181
