server:
  port: 8001
spring:
  application:
    name: snowflake-plus-sample
snowflake:
  plus:
    server-type: local
    name: snowflake-plus-sample
    listen-port: 8001
    address: localhost:2181
